### PR TITLE
Update installation command as per new name.

### PR DESCRIPTION
**Pull request by kunjee17**

### CODE REVIEW

**Comment by kunjee17** [comment]
My bad. sorry... I should give a issue for this.

**Comment by TheAngryByrd** [comment]
Small PRs are fine :) 👍

**Comment by TheAngryByrd** [comment]
Closes https://github.com/TheAngryByrd/Fable.Template.Library/issues/11

**Comment by kunjee17** [comment]
@TheAngryByrd thanks man. But even that is not working too. ;) . Can you please check what is the issue with installation. And thanks for accepting my PR.

**Comment by TheAngryByrd** [comment]
Oh it's because it's still prerelease.  Try using the exact version.

**Pull request merged**
